### ISSUE TITLE
Build Feed working on pipes.digital but not pipes CE

### ISSUE THREAD

**Issue by benfishbus** [pipes-digital/pipes#94]
I built [a feed at pipes.digital](https://www.pipes.digital/pipe/AO0wxlNK) that outputs successfully. I then built [the exact same feed in my Pipes CE environment](https://pipes.fishbulb.us/pipe/2vLGMK7j).

1. I noticed that in CE the Build Feed block doesn't include a "Recalculate GUID" checkbox.
2. When I view output, I get the following exception:

```
RSS::NotSetError at /feedpreview/2vLGMK7j
required variables of maker.channel are not set: link

    file: 0.9.rb location: to_feed line: 39 

BACKTRACE
/usr/local/lib/ruby/2.7.0/rss/maker/0.9.rb in to_feed
                raise NotSetError.new("maker.channel", _not_set_required_variables)
/usr/local/lib/ruby/2.7.0/rss/maker/base.rb in setup_channel
                @#{element}.to_feed(feed)
/usr/local/lib/ruby/2.7.0/rss/maker/0.9.rb in setup_elements
            setup_channel(rss)
/usr/local/lib/ruby/2.7.0/rss/maker/base.rb in to_feed
            setup_elements(feed)
/usr/local/lib/ruby/2.7.0/rss/maker/base.rb in make
            to_feed
/usr/local/lib/ruby/2.7.0/rss/maker/base.rb in make
              new(*args).make(&block)
/usr/local/lib/ruby/2.7.0/rss/maker.rb in make
            self[version].make(&block)
/pipes/blocks/builderblock.rb in process
            rss = RSS::Maker.make("rss2.0") do |maker|
/pipes/block.rb in run
            return self.process(processedInputs)
/pipes/block.rb in block in run
            inputs.each {|input| processedInputs << input&.run }
/pipes/block.rb in each
            inputs.each {|input| processedInputs << input&.run }
/pipes/block.rb in run
            inputs.each {|input| processedInputs << input&.run }
/pipes/pipe.rb in run
                    result = output.run
/pipes/server.rb in block in <top (required)>
        pipe_output = pipe.run(mode: :xml)
```

**Comment by onli** [comment]
Thanks for the report. https://github.com/pipes-digital/pipes/commit/ea379d5b613da2fc8906ba17a2295d23c7b3890e should fix that - it incorrectly sets the pipes.digital url, since we don't have access to the local url at that point, but at least that way the feed gets created.

**Comment by benfishbus** [comment]
The feed outputs correctly now, thank you! I still don't see a "Recalculate GUID" checkbox in the Build Feed block, but that was more a curiosity than a problem.
